### ISSUE TITLE
test(steps): increase coverage of nontrivial steps

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/ibis-ml#39] opened 2024-03-20 23:13 UTC

**Comment by jcrist** [comment] 2024-03-21 00:31
Oop, I think this is a duplicate of #35. Closing.

**Comment by jcrist** [comment] 2024-03-21 00:32
actually, since you split this out into two separate issues, lets keep this one and close #35.

**Comment by jitingxu1** [comment] 2024-05-28 23:15
all steps are covered by unit tests, if new one were found, we could reopen this.

**Closed by jitingxu1** 2024-05-28 23:15 UTC
